{% set name = "clearml" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/allegroai/clearml/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bcd536ef69f7c17edc411d9108b2c76c62edb40e4cedec3daaf7a63a72489859

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - clearml-init = clearml.cli.config.__main__:main
    - clearml-data = clearml.cli.data.__main__:main
    - clearml-task = clearml.cli.task.__main__:main
    - clearml-param-search = clearml.cli.hpo.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python >3.8
    - attrs >=18.0
    - furl >=2.0.0
    - jsonschema >=2.6.0
    - numpy >=1.10
    - pathlib2 >=2.3.0
    - pillow >=4.1.1
    - psutil >=3.4.2
    - pyparsing >=2.0.3
    - python-dateutil >=2.6.1
    - pyjwt >=2.4.0,<2.5.0
    - pyyaml >=3.12
    - requests >=2.20.0
    - six >=1.13.0
    - urllib3 >=1.21.1

test:
  imports:
    - clearml
  requires:
    - pip
  commands:
    - pip check
    - clearml-init --help
    - clearml-data --help
    - clearml-task --help
    - clearml-param-search --help

about:
  home: https://github.com/allegroai/clearml
  summary: Auto-Magical CI/CD to streamline your ML workflow. Experiment Manager, MLOps and Data-Management
  description: |
    Auto-Magical CI/CD to streamline your ML workflow.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://clear.ml/docs/
  dev_url: https://github.com/allegroai/clearml

extra:
  recipe-maintainers:
    - SimonBoothroyd
